(* the published wreath-recursion notation and the named library, asserted against the
   mathematics each entry's source states about it *)

(* ===================== The notation ===================== *)

(* the notation and the Mealy rule list are two presentations of one transducer, so the
   parser and AutomatonWreathRecursion invert each other up to nothing at all *)
VerificationTest[
	With[{entries = Select[AutomatonData[], ! MissingQ[AutomatonData[#]] &]},
		AllTrue[entries, name |-> With[{rule = AutomatonData[name]},
			Sort[AutomatonFromWreathString[AutomatonWreathRecursion[rule, Method -> "String"]]] === Sort[rule]]]],
	True
]

(* one automaton in the three permutation notations: cycles, the sigma of the paclet's own
   string form, and a 1-based image list *)
VerificationTest[
	With[{cycles = AutomatonFromWreathString["a = (a, b)(1,2), b = (a, b)"]},
		{AutomatonFromWreathString["a = \[Sigma](a, b), b = (a, b)"] === cycles,
		 AutomatonFromWreathString["a = (a, b)[2,1], b = (a, b)"] === cycles}],
	{True, True}
]

(* an omitted permutation is the identity and an omitted section is the trivial state, so the
   Grigorchuk generator a = (1,2) is the rooted transposition on two trivial sections *)
VerificationTest[
	AutomatonFromWreathString["a = (1,2)"],
	{{1, 0} -> {2, 1}, {1, 1} -> {2, 0}, {2, 0} -> {2, 0}, {2, 1} -> {2, 1}}
]

(* (1, 1, 1) repeats a letter and so is a section list, while (1, 2, 3) does not and so is a cycle *)
VerificationTest[
	AutomatonFromWreathString["a = (1, 1, 1)(1,2,3)"],
	{{1, 0} -> {2, 1}, {1, 1} -> {2, 2}, {1, 2} -> {2, 0}, {2, 0} -> {2, 0}, {2, 1} -> {2, 1}, {2, 2} -> {2, 2}}
]

(* a section that is an inverse or a product is not a state of the automaton it appears in,
   and no automaton over those generators realises the recursion *)
VerificationTest[
	{AutomatonFromWreathString["a = (1,2,3), b = (a, a^-1, b)"], AutomatonData["SidkiFree"]},
	{Missing["NonStateSections", {"a^-1"}], Missing["NonStateSections", {"a^2", "a^t"}]}
]

(* ===================== The library ===================== *)

(* every entry that is a Mealy machine is invertible: these are groups, not semigroups *)
VerificationTest[
	AllTrue[AutomatonData[], name |-> With[{rule = AutomatonData[name]}, MissingQ[rule] || InvertibleAutomatonQ[rule]]],
	True
]

(* the declared shape and the parsed automaton agree, for the flagged entries too *)
VerificationTest[
	AllTrue[AutomatonData[], name |-> With[{rule = AutomatonData[name]},
		MissingQ[rule] ||
			{AutomatonData[name, "States"], AutomatonData[name, "Colors"]} ===
				{Length @ Union[rule[[All, 1, 1]]], Length @ Union[rule[[All, 1, 2]]]}]],
	True
]

(* GAP's names resolve as aliases, and a name that resolves to nothing says what it nearly was *)
VerificationTest[
	{AutomatonData["GrigorchukGroup"] === AutomatonData["Grigorchuk"],
	 AutomatonData["BinaryAddingMachine"] === AutomatonData["AddingMachine"],
	 AutomatonData["Grigorchuck"]},
	{True, True, Missing["UnknownName", "Grigorchuck", {"Grigorchuk"}]}
]

(* ===================== What the sources assert ===================== *)

(* Grigorchuk 1980: four involutions on five states, and the automaton is the one this
   repository has been computing with all along *)
VerificationTest[
	With[{rule = AutomatonData["Grigorchuk"]},
		{Table[AutomatonWordOrder[rule, {g}, 8], {g, 4}], CanonicalAutomatonCode[rule]}],
	{{2, 2, 2, 2}, {1001163834, {5, 2}}}
]

(* Gupta-Sidki 1983: a and b have order 3, with a^-1 carried as its own state *)
VerificationTest[
	Table[AutomatonWordOrder[AutomatonData["GuptaSidki3"], {g}, 9], {g, 3}],
	{3, 3, 3}
]

(* the odometer: the level-L order is 2^L, so t has infinite order *)
VerificationTest[
	AutomatonWordOrders[AutomatonData["AddingMachine"], {1}, Range[8]],
	2 ^ Range[8]
]

(* the lamplighter's level orders plateau and then resume, which is why a level tower cannot
   certify infinite order and why a b^-1 is the involution rather than a or b *)
VerificationTest[
	With[{rule = AutomatonData["Lamplighter"]},
		{AutomatonWordOrders[rule, {1}, Range[8]], AutomatonWordOrder[rule, {1, -2}, 4]}],
	{{2, 4, 4, 8, 8, 8, 8, 16}, 2}
]

(* the classification numbers pin the three-state binary entries to their published rows *)
VerificationTest[
	BGKMNSSNumber /@ (AutomatonData /@ {"Aleshin", "Bellaterra", "BabyAleshin"}),
	{2240, 846, 2969}
]

(* Aleshin is free, so no generator has finite order; Bellaterra is generated by involutions *)
VerificationTest[
	{Table[AutomatonWordOrder[AutomatonData["Aleshin"], {g}, 12], {g, 3}],
	 Table[AutomatonWordOrder[AutomatonData["Bellaterra"], {g}, 12], {g, 3}]},
	{ConstantArray[Missing["OrderExceeds", 12], 3], {2, 2, 2}}
]

(* the Hanoi generators are the peg transpositions: involutions whose products are not *)
VerificationTest[
	With[{rule = AutomatonData["Hanoi3"]},
		{Table[AutomatonWordOrder[rule, {g}, 6], {g, 3}],
		 Table[AutomatonWordOrder[rule, {i, j}, 6], {i, 3}, {j, 3}] /. Missing["OrderExceeds", 6] -> Infinity}],
	{{2, 2, 2}, {{1, Infinity, Infinity}, {Infinity, 1, Infinity}, {Infinity, Infinity, 1}}}
]

(* every entry carries a reference key of References.md and a generator name per generator *)
VerificationTest[
	AllTrue[AutomatonData[], name |->
		StringQ[AutomatonData[name, "Reference"]] &&
			AllTrue[AutomatonData[name, "GeneratorNames"], StringQ] &&
			Length[AutomatonData[name, "GeneratorNames"]] <= AutomatonData[name, "States"]],
	True
]
